apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bookcatalog-chart.fullname" . }}
  labels:
    {{- include "bookcatalog-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "bookcatalog-chart.fullname" . }}
                port:
                  number: 80